DawidRosa/Models/ErrorViewModel.cs
using System;

namespace DawidRosa.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DawidRosa/Models/Model.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace EFGetStarted.AspNetCore.NewDb.Models
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        { }

        public DbSet<Data> Datas { get; set; }
    }

    public class Data
    {
        public int Id { get; set; }
        public string NameAndSurname { get; set; }
        public string Reason { get; set; }
        
    }
}

DawidRosa/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFGetStarted.AspNetCore.NewDb.Models;

namespace DawidRosa.Controllers
{
    public class DataController : Controller
    {
        private readonly DataContext _context;

        public DataController(DataContext context)
        {
            _context = context;
        }

        // GET: Data
        public async Task<IActionResult> Index()
        {
            return View(await _context.Datas.ToListAsync());
        }

        // GET: Data/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Datas
                .SingleOrDefaultAsync(m => m.Id == id);
            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // GET: Data/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Data/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameAndSurname,Reason")] Data data)
        {
            if (ModelState.IsValid)
            {
                _context.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(data);
        }

        // GET: Data/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Datas.SingleOrDefaultAsync(m => m.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }

        // POST: Data/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameAndSurname,Reason")] Data data)
        {
            if (id != data.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(data);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataExists(data.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(data);
        }

        // GET: Data/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Datas
                .SingleOrDefaultAsync(m => m.Id == id);
            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // POST: Data/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var data = await _context.Datas.SingleOrDefaultAsync(m => m.Id == id);
            _context.Datas.Remove(data);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataExists(int id)
        {
            return _context.Datas.Any(e => e.Id == id);
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
    }
}

DawidRosa/Views/Data/Contact.cshtml
@{
    ViewData["Title"] = "Kontakt";
}
<h2>@ViewData["Title"]</h2>
<h3>Dawid Rosa</h3>

<address>
    ul. Warszawska 86<br />
    21-080 Garbów<br />
    <abbr title="Telefon">Telefon: </abbr>
    504-077-166
</address>

<address>
    <strong>Email</strong> <a href="mailto:rosadawid94@gmial.com">Rosadawid94@gmail.com</a><br />
</address>

DawidRosa/Views/Data/Create.cshtml
@model EFGetStarted.AspNetCore.NewDb.Models.Data

@{
    ViewData["Title"] = "REKRUTACJA";
}

<h2>Jeśli chcesz dołączyć do Billenium</h2>

<h4>Uzupełnij pola poniżej</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <p><b>1. Imie i nazwisko</b></p>
                <input name="nameAndSurname" type="text" required placeholder="Imię i nazwisko" />

            </div>
            <div class="form-group">
                <p><b>2. Dlaczego chciałbyś uczestniczyć w praktykach?</b></p>
                <textarea name="reason" rows="10" cols="100" required placeholder="Napisz dlaczego..."></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Wyślij" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DawidRosa/Views/Data/Delete.cshtml
@model EFGetStarted.AspNetCore.NewDb.Models.Data

@{
    ViewData["Title"] = "Usuwanie wpisu";
}

<h2>Usuwanie wpisu</h2>

<h3>Czy na pewno chcesz usunąć wpis?</h3>
<div>
    <h4>Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imie i nazwisko:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NameAndSurname)
        </dd>
        <dt>
            Powód:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-default" /> |
        <a asp-action="Index">Wróć do bazy danych</a>
    </form>
</div>

DawidRosa/Views/Data/Details.cshtml
@model EFGetStarted.AspNetCore.NewDb.Models.Data

@{
    ViewData["Title"] = "Szczegóły";
}

<h2>Szczegóły</h2>

<div>
    <h4>Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imie i nazwisko:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NameAndSurname)
        </dd>
        <dt>
            Powód:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Wróć do bazy danych</a>
</div>

DawidRosa/Views/Data/Index.cshtml
@model IEnumerable<EFGetStarted.AspNetCore.NewDb.Models.Data>

@{
    ViewData["Title"] = "Baza danych";
}

<h2>Baza osób chętnych do firmy Billenium</h2>

<p>
    <a asp-action="Create">Utwórz nowy wpis</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Imie i nazwisko
                </th>
                <th>
                    Powód
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameAndSurname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reason)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Szczegóły</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>

DawidRosa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rekrutacja do Billenium</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Data" asp-action="Create" class="navbar-brand">Rekrutacja do Billenium</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Data" asp-action="Create">Strona główna</a></li>
                    <li><a asp-area="" asp-controller="Data" asp-action="Index">Baza danych</a></li>
                    <li><a asp-area="" asp-controller="Data" asp-action="Contact">Kontakt</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DawidRosa</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>